config/routes.rb
Rails.application.routes.draw do
  root "tops#index"
  resources :users, only: %i[new create]
  post 'colors', to: 'colors#create'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  get 'colors', to: 'colors#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html


  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/color.rb
class Color < ApplicationRecord
    belongs_to :user
    validates :mood_color_id, presence: true
    before_save :limit_one_day


    COLORS ={
    1 => "bg-sky-300",
    2 => "bg-red-500",
    3 => "bg-orange-300",
    4 => "bg-orange-500",
    5 => "bg-yellow-300",
    6 => "bg-yellow-500",
    7 => "bg-green-300",
    8 => "bg-green-500",
    9 => "bg-blue-300",
    10 => "bg-blue-500",
    11 => "bg-purple-300",
    12 => "bg-purple-500",
    13 => "bg-white",
    14 => "bg-black"
}.freeze


private

    def self.class_for_id(color_id)
        COLORS[color_id] || 'bg-gray-500'
    end

    def limit_one_day
        # 特定の日時が存在するかを確認
        if Color.exists?(user_id: self.user_id, created_at: Time.current.beginning_of_day..Time.current.end_of_day)
            errors.add(:base, I18n.t('activerecord.errors.models.color.messages.limit_one_per_day'))
            throw(:abort)
        end
    end
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  has_many :color

  validates :password, length: { minimum:3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates :first_name, presence: true, length: { maximum: 255 }
  validates :last_name, presence: true, length: { maximum: 255}
  validates :email, presence: true, uniqueness: true


end
# - password；最小で3文字以上必要（新規レコード作成もしくはcrypted_passwordカラムが更新される時のみ適応）
# - password_confirmation：値が空でないこと・passwordの値と一致すること（新規レコード作成もしくはcrypted_passwordカラムが更新される時のみ適応）
#- first_name：値が空でないこと・最大255文字以下であること
#- last_name：値が空でないこと・最大255文字以下であること
# email：値が空でないこと・ユニークな値であること

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login
  before_action :require_color

  add_flash_types :success, :danger

  private

  def not_authenticated
    redirect_to login_path, danger: 'ログインしてください'
  end

  def require_color
    @colors = Color.includes(:user).all
  end

end

app/controllers/colors_controller.rb
class ColorsController < ApplicationController

  def index;end

  def create
    @color = current_user.color.build(color_params)

    if @color.save
      redirect_to root_path, success: 'カラーボールが保存されました'
    else
      flash.now[:danger] = @color.errors.full_messages.join(", ")
      render "tops/index", status: :unprocessable_entity
    end
  end

  private

  def color_params
    params.require(:color).permit(:mood_color_id)
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  skip_before_action :require_login, only: %i[index]
  def index;end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new; end

  def create
    @user = login(params[:email], params[:password])

    if @user
      redirect_to root_path, success: 'ログインしました'
    else
      flash.now[:dager]= 'ログイン失敗しました'
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    logout
    redirect_to root_path, status: :see_other, success: 'ログアウトしました'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path, success: 'ユーザー登録が完了しました'
    else
      flash.now[:danger] = 'ユーザー登録に失敗しました'
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EmoticColor</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <% if logged_in? %>
      <%= render 'shared/header', colors: @colors %>
    <% else %>
      <%= render 'shared/before_login_header' %>
    <% end %>
      <%= render 'shared/flash_message' %>
     <%= yield %>   
    <%= render 'shared/footer' %>
    <script>
  document.querySelectorAll('.color-ball').forEach(function(ball){
    ball.addEventListener('click', function(){
      const colorId = this.getAttribute('data-color-id');
      document.getElementById('mood_color_id').value = colorId;
    });
  });
</script>
  </body>
</html>

app/views/shared/_before_login_header.html.erb
<header class="">
<div class="btm-nav top-0 z-10">
  <button class="bg-pink-200 text-pink-600">
    <svg
      xmlns="http://www.w3.org/2000/svg"
      class="h-5 w-5"
      fill="none"
      viewBox="0 0 24 24"
      stroke="currentColor">
      <path
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width="2"
        d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" />
    </svg>
    <%= link_to 'EmoticColor',root_path, class: "btm-nav-link"%>
  </button>
  <button class="active border-blue-600 bg-blue-200 text-blue-600">
    <svg
      xmlns="http://www.w3.org/2000/svg"
      class="h-5 w-5"
      fill="none"
      viewBox="0 0 24 24"
      stroke="currentColor">
      <path
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width="2"
        d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
    </svg>
    <span class="btm-nav-label"></span>
  </button>
  <button class="bg-teal-200 text-teal-600">
    <svg
      xmlns="http://www.w3.org/2000/svg"
      class="h-5 w-5"
      fill="none"
      viewBox="0 0 24 24"
      stroke="currentColor">
      <path
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width="2"
        d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />
    </svg>
    <span class="btm-nav-label">
         <%= link_to 'ログイン', login_path, class: "nav-link" %>
    </span>
  </button>
</div>  
</header>    

app/views/shared/_drawer.html.erb
<div class="drawer">
  <input id="my-drawer" type="checkbox" class="drawer-toggle" />
  <div class="drawer-content">

    <!-- ドロワー開閉ボタン -->
    <label for="my-drawer" class="drawer-button cursor-pointer">Open drawer</label>
  </div>
  <div class="drawer-side">
  <%# ドロワー制御コード %>
    <label for="my-drawer" aria-label="close sidebar" class="drawer-overlay"></label>
    <ul class="menu bg-none text-base-content min-h-full w-100 p-8">
      <!-- ここから　ドロワー内のスライダーメニュー -->
<%# 一覧テーブル %>

<% @colors.each do |color| %>
<% if color && color.mood_color_id.present? %>

<% color_class = Color.class_for_id(color.mood_color_id.to_i) %>

<div class="overflow-x-auto border-l-black rounded-md shadow-lg bg-white my-4">
  <table class="table rounded-md shadow-md">
    <thead>
      <tr>
        <th><%= l color.created_at, format: :short%></th>
        <th>今日の私の気分</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>
          <div class="flex items-center gap-3">
            <div class="avatar">
                <div class="avatar online placeholder">
                  <div class="bg-neutral text-neutral-content w-16 rounded-full">
                    <span class="text-xl">AI</span>
                  </div>
                </div>
            </div>
            <div>
              <div class="font-bold"><%= color.user.first_name %> <%= color.user.last_name %></div>
            </div>
          </div>
        </td>

        <td><div class="color-ball w-10 h-10 rounded-full mx-auto <%= color_class %>"></div></td>
      </tr>
  </table>
</div>
<%# ここまで %>
<% else %>
<p>no colors</p>
<% end %>
<% end %>

    </ul>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
<% if flash[:success] %>
<div role="alert" class="relative z-50 ">
  <div class="border border-t-0 absolute top-2/4 border-green-400 shadow-md rounded-md py-4 px-2 my-3 mx-3  text-white bg-green-400">
    <%= message_type %> :
    <%= message %>
  </div>
</div>
<% else %>
<div role="alert" class="relative z-50">
  <div class="border border-t-0 absolute top-3/4 border-red-400 shadow-md rounded-md py-4 px-2 my-3 mx-3  text-white bg-red-400">
    <%= message_type %> :
    <%= message %>
  </div>
</div>
<% end %>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer bg-neutral text-neutral-content items-center p-4 ">
  <aside class="grid-flow-col items-center">
    <svg
      width="36"
      height="36"
      viewBox="0 0 24 24"
      xmlns="http://www.w3.org/2000/svg"
      fill-rule="evenodd"
      clip-rule="evenodd"
      class="fill-current">
      <path
        d="M22.672 15.226l-2.432.811.841 2.515c.33 1.019-.209 2.127-1.23 2.456-1.15.325-2.148-.321-2.463-1.226l-.84-2.518-5.013 1.677.84 2.517c.391 1.203-.434 2.542-1.831 2.542-.88 0-1.601-.564-1.86-1.314l-.842-2.516-2.431.809c-1.135.328-2.145-.317-2.463-1.229-.329-1.018.211-2.127 1.231-2.456l2.432-.809-1.621-4.823-2.432.808c-1.355.384-2.558-.59-2.558-1.839 0-.817.509-1.582 1.327-1.846l2.433-.809-.842-2.515c-.33-1.02.211-2.129 1.232-2.458 1.02-.329 2.13.209 2.461 1.229l.842 2.515 5.011-1.677-.839-2.517c-.403-1.238.484-2.553 1.843-2.553.819 0 1.585.509 1.85 1.326l.841 2.517 2.431-.81c1.02-.33 2.131.211 2.461 1.229.332 1.018-.21 2.126-1.23 2.456l-2.433.809 1.622 4.823 2.433-.809c1.242-.401 2.557.484 2.557 1.838 0 .819-.51 1.583-1.328 1.847m-8.992-6.428l-5.01 1.675 1.619 4.828 5.011-1.674-1.62-4.829z"></path>
    </svg>
    <p>Copyright © 2024 - All right reserved</p>
  </aside>
  <nav class="grid-flow-col gap-4 md:place-self-center md:justify-self-end">
    <a>
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="24"
        height="24"
        viewBox="0 0 24 24"
        class="fill-current">
        <path
          d="M24 4.557c-.883.392-1.832.656-2.828.775 1.017-.609 1.798-1.574 2.165-2.724-.951.564-2.005.974-3.127 1.195-.897-.957-2.178-1.555-3.594-1.555-3.179 0-5.515 2.966-4.797 6.045-4.091-.205-7.719-2.165-10.148-5.144-1.29 2.213-.669 5.108 1.523 6.574-.806-.026-1.566-.247-2.229-.616-.054 2.281 1.581 4.415 3.949 4.89-.693.188-1.452.232-2.224.084.626 1.956 2.444 3.379 4.6 3.419-2.07 1.623-4.678 2.348-7.29 2.04 2.179 1.397 4.768 2.212 7.548 2.212 9.142 0 14.307-7.721 13.995-14.646.962-.695 1.797-1.562 2.457-2.549z"></path>
      </svg>
    </a>
    <a>
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="24"
        height="24"
        viewBox="0 0 24 24"
        class="fill-current">
        <path
          d="M19.615 3.184c-3.604-.246-11.631-.245-15.23 0-3.897.266-4.356 2.62-4.385 8.816.029 6.185.484 8.549 4.385 8.816 3.6.245 11.626.246 15.23 0 3.897-.266 4.356-2.62 4.385-8.816-.029-6.185-.484-8.549-4.385-8.816zm-10.615 12.816v-8l8 3.993-8 4.007z"></path>
      </svg>
    </a>
    <a>
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="24"
        height="24"
        viewBox="0 0 24 24"
        class="fill-current">
        <path
          d="M9 8h-3v4h3v12h5v-12h3.642l.358-4h-4v-1.667c0-.955.192-1.333 1.115-1.333h2.885v-5h-3.808c-3.596 0-5.192 1.583-5.192 4.615v3.385z"></path>
      </svg>
    </a>
  </nav>
</footer>

app/views/shared/_form.html.erb
<%= form_with model: @color ||Color.new, url: colors_path, local: true  do |f|%>
            <div class="color_list mb-10 pl-5 ">
                <div class="color_selection grid grid-flow-col mb-10 animation-float">
                    <button type="button" class="color-ball w-16 active:animate-ping focus:animate-none h-16 bg-red-300 hover:animate-float_up rounded-full" data-color-id="1"></button>
                    <button type="button" class="color-ball w-16 active:animate-ping focus:animate-none h-16 bg-orange-300 hover:animate-float_up rounded-full " data-color-id="3"></button>     
                    <button type="button" class="color-ball w-16 active:animate-ping focus:animate-none h-16 bg-yellow-300 hover:animate-float_up rounded-full " data-color-id="5"></button>
                    <button type="button" class="color-ball w-16 active:animate-ping focus:animate-none h-16 bg-green-300 hover:animate-float_up rounded-full " data-color-id="7"></button>
                    <button type="button" class="color-ball w-16 active:animate-ping focus:animate-none h-16 bg-blue-300 hover:animate-sink_down rounded-full " data-color-id="9"></button>
                    <button type="button" class="color-ball w-16 active:animate-ping focus:animate-none h-16 bg-purple-300 hover:animate-sink_down rounded-full " data-color-id="11"></button>
                    <button type="button" class="color-ball w-16 active:animate-ping focus:animate-none h-16 bg-white outline hover:animate-float_up outline-slate-100 rounded-full "data-color-id="13"></button>
                </div>
                <div class="color_selection grid grid-flow-col ">
                    <button type="button" class="color-ball w-16 active:animate-ping focus:animate-none   h-16 bg-red-500 hover:animate-float_up rounded-full " data-color-id="2"></button>
                    <button type="button" class="color-ball w-16 active:animate-ping focus:animate-none   h-16 bg-orange-500 hover:animate-float_up rounded-full " data-color-id="4"></button>      
                    <button type="button" class="color-ball w-16 active:animate-ping focus:animate-none   h-16 bg-yellow-500 hover:animate-float_up rounded-full " data-color-id="6"></button>
                    <button type="button" class="color-ball w-16 active:animate-ping focus:animate-none   h-16 bg-green-500 hover:animate-float_up rounded-full " data-color-id="8"></button>
                    <button type="button" class="color-ball w-16 active:animate-ping focus:animate-none   h-16 bg-blue-500 hover:animate-sink_down rounded-full " data-color-id="10"></button>
                    <button type="button" class="color-ball w-16 active:animate-ping focus:animate-none   h-16 bg-purple-500 hover:animate-sink_down rounded-full " data-color-id="12"></button>
                    <button type="button" class="color-ball w-16 active:animate-ping focus:animate-none   h-16 bg-black hover:animate-sink_down rounded-full " data-color-id="14"></button>
                </div>
            </div>

            <%= f.hidden_field :mood_color_id, id: 'mood_color_id' %>
            <%= button_tag type: "submit", class: "btn btn-secondary h-20 w-40 btn-xs sm:btn-sm md:btn-md lg:btn-lg animate-button_up hover:animate-none" do %>  
            <p class=""></p>カラーを提出</P>
            <% end %>
<% end %>

app/views/shared/_header.html.erb
<header class="">
<div class="btm-nav top-0 z-10">
  <button class="bg-pink-200 text-pink-600">
    <svg
      xmlns="http://www.w3.org/2000/svg"
      class="h-5 w-5"
      fill="none"
      viewBox="0 0 24 24"
      stroke="currentColor">
      <path
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width="2"
        d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" />
    </svg>
    <%= link_to 'EmoticColor',root_path, class: "btm-nav-link"%>
  </button>
  <button class="active border-blue-600 bg-blue-200 text-blue-600">
    <svg
      xmlns="http://www.w3.org/2000/svg"
      class="h-5 w-5"
      fill="none"
      viewBox="0 0 24 24"
      stroke="currentColor">
      <path
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width="2"
        d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
    </svg>
    <span class="btm-nav-label">投稿者一覧<%= render 'shared/drawer', colors: @colors%></span>
  </button>
  <button class="bg-teal-200 text-teal-600">
    <svg
      xmlns="http://www.w3.org/2000/svg"
      class="h-5 w-5"
      fill="none"
      viewBox="0 0 24 24"
      stroke="currentColor">
      <path
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width="2"
        d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />
    </svg>
    <span class="btm-nav-label">
     <%= link_to 'ログアウト', logout_path, class: "nav-link", data: { turbo_method: :delete } %>
    </span>
  </button>
</div>  
</header>
      

app/views/tops/index.html.erb
        <%= image_tag ("top.jpg"), class: "relative bg-center w-full bg-no-repeat bg-cover h-auto min-h-screen" %>
        <div class="absolute inset-0 flex justify-center items-center text-3xl text-center">

          <div style="height: 400px; padding-left: 70px; border-radius: 2rem;" class="artboard artboard-horizontal phone-6 grid grid-rows-2 bg-white">
              <div style="padding-top: 50px;" class="fieeling_section ">
                    <h2 style="padding-bottom: 12px;">今日の気分は？</h2>
                    <label class="text-3xl lg:text-2xl md:text-lg sm:text-md ">
                      あなたの今の気分をカラーボールから<br>直感で選んでみてください
                    </label>
              </div>
              <%= render 'shared/form', color: @color %>
          </div>
        </div>
      </div>

app/views/user_sessions/new.html.erb
      <%= render 'shared/flash_message' %>
      <div class="mt-28 ml-8">
    <h1 class="text-3xl font-bold ">ログイン</h1>
      <%= form_with url: login_path, class:"h-auto" do |f| %>
        <div class="mb-3 mx-auto">
          <%= f.label :email, class:""%>
          <%= f.email_field :email, class: "input input-bordered flex items-center grow" %>
        </div>
        <div class="mb-3">
          <%= f.label :password, class: "" %>
          <%= f.password_field :password, class: "input input-bordered flex items-center grow" %>
        </div>
        <%= f.submit "ログイン", class: "btn btn-secondary h-20 w-40 btn-xs sm:btn-sm md:btn-md lg:btn-lg animate-button_up hover:animate-none" %>
      <% end %>
      <div class='text-center'>
        <%= link_to '登録ページへ', new_user_path %>
        <%= link_to 'パスワードをお忘れの方はこちら', '#' %>
      </div>
      </div>

app/views/users/new.html.erb
     <h1>ユーザー登録</h1>
      <%= form_with model: @user, class:"mt-28 ml-8" do |f| %>
        <div class="mb-3">
          <%= f.label :firts_name, class: "grow"%>
          <%= f.text_field :first_name, class: "input input-bordered flex items-center grow" %>
        </div>
        <div class="mb-3">
          <%= f.label :last_name, class: "grow" %>
          <%= f.text_field :last_name, class: "input input-bordered flex items-center gap-2 grow" %>
        </div>
        <div class="mb-3">
          <%= f.label :email, class: "grow" %>
          <%= f.email_field :email, class: "input input-bordered flex items-center gap-2 grow" %>
        </div>
        <div class="mb-3">
          <%= f.label :password, class: "grow" %>
          <%= f.password_field :password, class: "input input-bordered flex items-center gap-2 grow" %>
        </div>
        <div class="mb-3">
          <%= f.label :password_confirmation, class: "grow" %>
          <%= f.password_field :password_confirmation, class: "input input-bordered flex items-center gap-2 grow" %>
        </div>
        <%= f.submit "登録", class: "btn btn-secondary h-20 w-40 btn-xs sm:btn-sm md:btn-md lg:btn-lg animate-button_up hover:animate-none" %>
      <% end %>
      <div class='text-center'>
        <%= link_to 'ログインページへ', login_path %>
      </div>